#include "p0_build_config.h"

#define P0_STRINGIFY_INNER(value) #value
#define P0_STRINGIFY(value) P0_STRINGIFY_INNER(value)

const char p0_firmware_manifest[]
    __attribute__((used, section(".firmware_manifest"))) =
        "P0_H60_SAFE;FW=" P0_FIRMWARE_BUILD_LABEL ";MOTION="
        P0_STRINGIFY(P0_MOTION_OUTPUT_COMPILED)
        ";CAL=" P0_STRINGIFY(P0_MOTION_CALIBRATION_VALID)
        ";M2A=" P0_STRINGIFY(P0_M2A_CALIBRATION_BUILD)
        ";TIMEOUT_MS=250;UART_RX=IRQ256-R1"
#if P0_IWDG_DIAGNOSTIC_BUILD != 0
        ";IWDG_HARDFAULT_DIAG=1;TRIGGER_MS=1500;MOTION_LOCKED=1"
#elif P0_W2_FIVE_SECOND_LINK_LOSS_BUILD != 0
        ";PWM=W2-FOUR-5K-R1;WAKE_MS=3;STOP=GPIO00;FOUR_CHANNEL_PROFILE=1;"
        "PROFILE_CHANNEL=240;FORWARD_SIGNS=-1,+1,-1,+1;DUTY=80;"
        "HOLD_LEASE_MS=75;MAX_ARMED_MS=5000;DIRECTION_CHANGE_REARM=1;"
        "LINK_LOSS_CANDIDATE=1"
#elif P0_W2_FOUR_WHEEL_PROFILE_BUILD != 0
        ";PWM=W2-FOUR-5K-R1;WAKE_MS=3;STOP=GPIO00;FOUR_CHANNEL_PROFILE=1;"
        "PROFILE_CHANNEL=240;FORWARD_SIGNS=-1,+1,-1,+1;DUTY=80;"
        "HOLD_LEASE_MS=75;MAX_ARMED_MS=1000;DIRECTION_CHANGE_REARM=1"
#elif P0_H6_EXTENDED_WINDOW_BUILD != 0
        ";PWM=H6-SINGLE-5K-R2;WAKE_MS=3;STOP=GPIO00;ONE_CHANNEL_PER_ARM=1;"
        "MC_PLUS_80_ONLY=1;HOLD_LEASE_MS=75;MAX_ARMED_MS=2500;"
        "ENVELOPE_MS=300,1200,300;HOST_NONZERO_MAX_MS=1800"
#elif P0_H6_CHARACTERIZATION_BUILD != 0
        ";PWM=H6-SINGLE-5K-R1;WAKE_MS=3;STOP=GPIO00;ONE_CHANNEL_PER_ARM=1;"
        "MIN_DUTY=50;MAX_DUTY=120;HOLD_LEASE_MS=75;MAX_ARMED_MS=1000"
#elif P0_M2A_SLOWDRIVE_BUILD != 0
        ";PWM=SLOW5K-MB-PLUS-50-R1;WAKE_MS=3;STOP=GPIO00"
#elif P0_M2A_CALIBRATION_BUILD != 0
        ";PWM=M2A5K-R1;MIN_DUTY=50"
#endif
        ;
